Upgrade to SpatialOS 13.0.0
spatialos/UnrealBasicsTutorial pull request #1
Opened 2018-05-15 13:53 UTC by improbable-valentyn

Upgrade to SpatialOS 13.0.0 and migrate to the Unreal SDK 1.0.0 using [this guide](https://github.com/spatialos/UnrealSDK/blob/master/docs/migration.md).
Tests performed:
* Building and running the project locally
* Deploying to the cloud and starting a client from the launcher
  * Known issue: the client can't connect to a cloud deployment when started from the launcher. Workaround: apply the patch from [this PR](https://github.com/EpicGames/UnrealEngine/pull/4206) in your UnrealEngine checkout

2018-05-15 15:34 UTC, jared-improbable requested changes
The Generated/ and Plugins/*/Binaries/ folders shouldn't be committed.

2018-05-16 10:06 UTC, jared-improbable approved these changes

2018-05-16 10:06 UTC, jared-improbable commented on workers/unreal/Game/Plugins/SpatialOS/SpatialOSEditorToolbar/Binaries/Win64/UE4Editor.modules
> +{
This folder needs ignoring, too

2018-05-16 10:11 UTC, jared-improbable approved these changes

2018-05-16 10:14 UTC, ElleEss approved these changes
I checked the link, just in case. (Obsessed with broken links.)

2018-05-16 10:21 UTC, ElleEss approved these changes
Be good to use the 'SpatialOS Unreal SDK' name that's in the docs to avoid confusion. See comment in-line.

2018-05-16 10:49 UTC, oblm approved these changes

2018-05-16 11:00 UTC, merged